In [1]:
import pandas as pd

In [4]:
pd.read_pickle('./test_cost/df_test_costs8_100_dnn_final_test_noClass.pkl')#.loc[0.5,1.5]

,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0
0.5,"(0.00021853606449440122, 0.6614823937416077, 3...","(0.0003696703934110701, 0.6257262825965881, 29...","(0.0005287356907501817, 0.5680392384529114, 28...","(0.0005192421958781779, 0.5765491127967834, 25...","(0.0004292865633033216, 0.4282679557800293, 24...","(0.0005927909514866769, 0.56321120262146, 23.8...","(0.0003415231767576188, 0.5503919124603271, 23...","(0.0005656771827489138, 0.43700695037841797, 2...","(0.0005852505564689636, 0.4783712327480316, 21...",931230,"(0.00035573862260207534, 0.46660733222961426, ...","(0.0008515008958056569, 0.47117146849632263, 2...","(0.0005612169625237584, 0.4647084176540375, 20...","(0.0007112843450158834, 0.538141131401062, 22....","(0.000609633163549006, 0.5357373356819153, 19....","(0.0004204583528917283, 0.5956467390060425, 20...","(0.00030970267835073173, 0.50896817445755, 21....",931230,931230,931230
1.0,931230,931230,931230,931230,931230,931230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
pd.read_pickle('./test_cost/df_test_costs8_20000_dnn_final_test_noClass.pkl')#.loc[0.5,1.5]

,0.5,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0
0.5,"(0.05248630419373512, 0.43200522661209106, 192...","(0.03671618923544884, 0.36861374974250793, 173...","(0.027762984856963158, 0.32491323351860046, 15...","(0.02193882316350937, 0.3358215391635895, 146....","(0.02181863598525524, 0.25591689348220825, 133...","(0.019141264259815216, 0.33060163259506226, 14...","(0.017299512401223183, 0.30730125308036804, 13...","(0.01575746014714241, 0.25253182649612427, 124...","(0.014770766720175743, 0.27433139085769653, 12...","(0.017895078286528587, 0.26239320635795593, 12...","(0.014287244528532028, 0.26924288272857666, 12...","(0.015617339871823788, 0.2568942606449127, 127...","(0.015988485887646675, 0.2535015940666199, 119...","(0.01274600625038147, 0.2717534601688385, 124....","(0.013147952035069466, 0.29032957553863525, 12...","(0.013179494999349117, 0.3086584210395813, 130...","(0.014662599191069603, 0.29262498021125793, 13...","(0.01304681971669197, 0.23482736945152283, 117...","(0.013368505984544754, 0.33435818552970886, 12...","(0.014361809939146042, 0.24593649804592133, 12..."
1.0,931230,"(0.03421911969780922, 0.25950366258621216, 151...","(0.028848309069871902, 0.24488046765327454, 13...","(0.022520488128066063, 0.23374876379966736, 12...","(0.018385024741292, 0.20230132341384888, 116.3...","(0.02066722884774208, 0.1768486648797989, 112....","(0.015521791763603687, 0.19775883853435516, 11...","(0.015768304467201233, 0.18187715113162994, 11...","(0.014089930802583694, 0.19999179244041443, 11...","(0.014605971984565258, 0.16119475662708282, 10...","(0.013799183070659637, 0.22079864144325256, 11...","(0.014390845783054829, 0.17988350987434387, 10...","(0.013114575296640396, 0.1630622297525406, 104...","(0.013087227940559387, 0.17921903729438782, 10...","(0.01220160536468029, 0.1555507928133011, 95.2...","(0.015080765821039677, 0.15615546703338623, 10...","(0.011536963284015656, 0.16707733273506165, 10...","(0.012701171450316906, 0.1720712035894394, 102...","(0.010989117436110973, 0.1603790521621704, 99....","(0.014138732105493546, 0.19320125877857208, 10..."
1.5,"(0.052291978150606155, 0.25599896907806396, 15...","(0.033887431025505066, 0.20743395388126373, 12...","(0.022635720670223236, 0.16299304366111755, 11...","(0.022508706897497177, 0.19660499691963196, 11...","(0.01675114780664444, 0.17285580933094025, 110...","(0.01519282627850771, 0.14409740269184113, 106...","(0.01352186594158411, 0.12444590777158737, 90....","(0.012743922881782055, 0.11385968327522278, 90...","(0.013893966563045979, 0.1331067532300949, 98....","(0.012434069067239761, 0.14941659569740295, 98...","(0.013075878843665123, 0.13498127460479736, 98...","(0.012247406877577305, 0.14688198268413544, 99...","(0.01186333131045103, 0.12652228772640228, 92....","(0.010107708163559437, 0.14457441866397858, 93...","(0.010800313204526901, 0.11449737846851349, 89...","(0.011325595900416374, 0.13615001738071442, 96...","(0.011820861138403416, 0.10985027998685837, 84...","(0.011687010526657104, 0.13660909235477448, 96...","(0.010980899445712566, 0.1104394868016243, 78....","(0.011114010587334633, 0.10392142087221146, 76..."
2.0,"(0.04837728291749954, 0.20724931359291077, 138...","(0.02871563658118248, 0.17087596654891968, 121...","(0.019121451303362846, 0.15040290355682373, 10...","(0.017448624595999718, 0.13687355816364288, 99...","(0.015035439282655716, 0.12097232043743134, 97...","(0.01225967239588499, 0.10711706429719925, 85....","(0.012365012429654598, 0.12288966774940491, 91...","(0.012047987431287766, 0.11877094209194183, 88...","(0.010507849976420403, 0.09997142106294632, 76...","(0.010560842230916023, 0.1022728681564331, 84....","(0.010557174682617188, 0.11087851226329803, 80...","(0.010450312867760658, 0.09150681644678116, 73...","(0.010426582768559456, 0.10084298253059387, 85...","(0.010823183692991734, 0.1100817322731018, 84....","(0.009584266692399979, 0.09913209080696106, 76...","(0.011148769408464432, 0.1034717783331871, 84....","(0.010126795619726181, 0.09525050222873688, 75...","(0.009770696982741356, 0.08911095559597015, 71...","(0.008715429343283176, 0.09770375490188599, 75...","(0.011583146639168262, 0.10676702111959457, 79..."
2.5,"(0.04196539148688316, 0.19458726048469543, 128...","(0.02393193542957306, 0.1341148018836975, 104....","(0.01867574080824852, 0.11905988305807114, 97....","(0.013840293511748314, 0.10386163741350174, 83...","(0.01216354314237833, 0.09315175563097, 75.533...","(0.011992230080068111, 0.09274949133396149, 78...","(0.011373473331332207, 0.08263083547353745, 74...","(0.009792698547244072, 0.07416107505559921, 71...","(0.009053259156644344, 0.08886177837848663, 69...","(0.010333353653550148, 0.09515538066625595, 74...","(0.010656711645424366, 0.08389357477426529, 75...","(0.00890769250690937, 0.0852687656879425, 69.6...","(0.010009272955358028, 0.08542740345001221, 72...","(0.009398982860147953, 0.08536455035209656, 72...","(0.009387507103383541, 0.08456660062074661, 68...","(0.009430332109332085, 0.07320484519004822, 61...","(0.009295253083109856, 0.07431051880121231, 69...","(0.008010389283299446, 0.0704292356967926, 61....","(0.008545948192477226, 0.06614824384450912, 60...","(0.009308596141636372, 0.09500914067029953, 78..."
3.0,"(0.043083690106868744, 0.1506713181734085, 117...","(0.02294335700571537, 0.12733858823776245, 99....","(0.016659779474139214, 0.09483141452074051, 84...","(0.013848002068698406, 0.08386019617319107, 82...","(0.010794302448630333, 0.09146822988986969, 73...","(0.011088996194303036, 0.09011520445346832, 74...","(0.009202501736581326, 0.08486754447221756, 69...","(0.009813519194722176, 0.07225184887647629, 67...","(0.009760692715644836, 0.0719183012843132, 67....","(0.00819011777639389, 0.07431642711162567, 66....","(0.00911214854568243, 0.0768614262342453, 68.8...","(0.007708136457949877, 0.06775521486997604, 59...","(0.008799620904028416, 0.06784049421548843, 65...","(0.011806309223175049, 0.07489366829395294, 65...","(0.008640234358608723, 0.06553731858730316, 57...","(0.0073074353858828545, 0.06374402344226837, 5...","(0.007443511858582497, 0.06625910848379135, 61...","(0.007961835712194443, 0.07619640231132507, 64...","(0.007694983389228582, 0.06827207654714584, 61...","(0.010727026499807835, 0.04881767928600311, 51..."
3.5,"(0.04002106934785843, 0.14605168998241425, 114...","(0.020969588309526443, 0.10947200655937195, 92...","(0.01451075728982687, 0.0845005065202713, 78.0...","(0.011908432468771935, 0.0797279104590416, 76....","(0.011819512583315372, 0.06656823307275772, 68...","(0.009908262640237808, 0.06869319826364517, 68...","(0.008809639140963554, 0.08290954679250717, 68...","(0.009264031425118446, 0.06139468029141426, 60...","(0.008505886420607567, 0.06718514859676361, 64...","(0.008469541557133198, 0.060641493648290634, 6...","(0.008485513739287853, 0.05563938245177269, 57...","(0.0066018300130963326, 0.06497891247272491, 5...","(0.007352156098932028, 0.05430278182029724, 56...","(0.00711396150290966, 0.06580249965190887, 62....","(0.007815473712980747, 0.06496042013168335, 61...","(0.006716102361679077, 0.05848906189203262, 57...","(0.007706072647124529, 0.05584410950541496, 59...","(0.006958562880754471, 0.049377478659152985, 5...","(0.006899322383105755, 0.05922365188598633, 58...","(0.006394036114215851, 0.0501428060233593, 53...."
4.0,"(0.03980712592601776, 0.1412120908498764, 117....","(0.020519277080893517, 0.0940849781036377, 86....","(0.01398954726755619, 0.07009552419185638, 74....","(0.0108399773016572, 0.06931611895561218, 67.4...","(0.009375938214361668, 0.06793844699859619, 67...","(0.014912963844835758, 0.060089852660894394, 6...","(0.008763542398810387, 0.05266574025154114, 59...","(0.008278736844658852, 0.06494361907243729, 64...","(0.007173065561801195, 0.06281187385320663, 61...","(0.006734252907335758, 0.048218563199043274, 5...","(0.007745456416159868, 0.05518415942788124, 59...","(0.006808171514421701, 0.0546407550573349, 59....","(0.006952017080038786, 0.052457112818956375, 5...","(0.007650538347661495, 0.05769048258662224, 58...","(0.0065719494596123695, 0.06111054867506027, 6...","(0.006295827217400074, 0.04685045778751373, 54...","(0.006603257730603218, 0.05781427025794983, 56...","(0.006940782070159912, 0.059638142585754395, 5...","(0.006866107229143381, 0.04298936575651169, 50...","(0.006455493159592152, 0.04525658115744591, 54..."
4.5,"(0.03911725804209709, 0.14177566766738892, 115...","(0.01889202557504177, 0.08321613073348999, 80....","(0.012642822228372097, 0.07165001332759857, 74...","(0.010426368564367294, 0.06275812536478043, 69...","(0.00836973823606968, 0.05638715624809265, 60....","(0.008871542289853096, 0.05415322631597519, 62...","(0.00787272583693266, 0.0661538690328598, 64.1...","(0.008048290386795998, 0.054865408688783646, 5...","(0.007079713977873325, 0.049509648233652115, 5...","(0.0072175548411905766, 0.049888696521520615, ...","(0.005961413960903883, 0.0432409942150116, 51....","(0.006541351322084665, 0.05128448083996773, 54...","(0.00709678465500474, 0.047570373862981796, 55...","(0.007285920437425375, 0.0467023141682148, 54....","(0.007140077650547028, 0.04729389399290085, 56...","(0.006056595593690872, 0.044277675449848175, 5...","(0.005991361569613218, 0.04788409173488617, 53...","(0.006477970629930496, 0.04751833900809288, 53...","(0.005674263928085566, 0.04223485291004181, 48...","(0.005618859548121691, 0.055656276643276215, 5..."
5.0,"(0.035603683441877365, 0.11572358757257462, 10...","(0.020625123754143715, 0.08499343693256378, 85...","(0.01293422095477581, 0.06984463334083557, 72....","(0.009919209405779839, 0.05911897495388985, 65...","(0.00917054247111082, 0.05736988037824631, 64....","(0.00792558304965496, 0.0488278903067112, 59.0...","(0.007288639433681965, 0.047891389578580856, 5...","(0.008433832786977291, 0.05187496915459633, 59...","(0.006924128625541925, 0.05512299761176109, 57...","(0.006228877697139978, 0.04651821777224541, 55...","(0.006681236904114485, 0.038990240544080734, 5...","(0.006767050828784704, 0.044054873287677765, 5...","(0.006777862552553415, 0.045030418783426285, 5...","(0.006591533310711384, 0.04579043388366699, 56...","(0.006145216058939695, 0.047996219247579575, 5...","(0.005791733507066965, 0.040707629173994064, 5...","(0.005697145592421293, 0.04366201162338257, 49...","(0.005976174958050251, 0.039193589240312576, 4...","(0.005666682962328196, 0.04335658997297287, 49...","(0.006319292820990086, 0.04898000881075859, 55..."
5.5,"(0.033117953687906265, 0.11435253918170929, 10...","(0.01811263896524906, 0.0695471540093422, 80.1...","(0.011826461181044579, 0.058431707322597504, 6...","(0.010208817198872566, 0.06019212678074837, 63...","(0.008554389700293541, 0.050745412707328796, 6...","(0.008068064227700233, 0.046746328473091125, 5...","(0.007166402880102396, 0.05109480395913124, 56...","(0.0065388428047299385, 0.04000135511159897, 5...","(0.005982428789138794, 0.04485167935490608, 52...","(0.006176256574690342, 0.04164297878742218, 52...","(0.007096659857779741, 0.04388459399342537, 54...","(0.006048213690519333, 0.050261858850717545, 5...","(0.006108760833740234, 0.047922782599925995, 5...","(0.006093666888773441, 0.04808221384882927, 54...","(0.0060342466458678246, 0.04086429253220558, 5...","(0.005691641476005316, 0.04155581444501877, 51...","(0.0052028014324605465, 0.03277837857604027, 4...","(0.005728243850171566, 0.03799847885966301, 49...","(0.0050071654841303825, 0.030664905905723572, ...","(0.00540395500138402, 0.042085886001586914, 50..."
6.0,"(0.03565819561481476, 0.11503568291664124, 108...","(0.01819355972111225, 0.07673961669206619, 81....","(0.012762797996401787, 0.0659855306148529, 72....","(0.008927837945520878, 0.05497604236006737, 61...","(0.007934639230370522, 0.047412775456905365, 5...","(0.007899281568825245, 0.04293246939778328, 56...","(0.006593757309019566, 0.04097897186875343, 56...","(0.006592244375497103, 0.04041319340467453, 51...","(0.0064118290320038795, 0.04401632398366928, 5...",931230,"(0.005943428725004196, 0.04182927682995796, 50...","(0.005803805775940418, 0.03821032494306564, 51...","(0.00614370871335268, 0.0376182422041893, 50.9...","(0.005033324938267469, 0.03077264130115509, 45...","(0.005432167090475559, 0.040403857827186584, 4...","(0.0054674590937793255, 0.040813520550727844, ...","(0.0055175344459712505, 0.030493104830384254, ...","(0.005805487744510174, 0.03737703710794449, 49...","(0.005165687296539545, 0.03636787831783295, 46...","(0.0052775004878640175, 0.03525935113430023, 4..."
6.5,"(0.03357159346342087, 0.10347463935613632, 101...","(0.01718553714454174, 0.07234212756156921, 77....","(0.012090197764337063, 0.057875584810972214, 6...","(0.010433975607156754, 0.05667272210121155, 63...","(0.008550588972866535, 0.042639948427677155, 5...","(0.008034924976527691, 0.044203296303749084, 5...","(0.007202914450317621, 0.04196995869278908, 55...","(0.006208338309079409, 0.03558305650949478, 53...","(0.0064627607353031635, 0.03899972140789032, 5...","(0.006992869544774294, 0.039414387196302414, 5...","(0.00658566365018487, 0.0371735505759716, 53.3...","(0.005501460749655962, 0.03561713919043541, 50...","(0.006038653198629618, 0.03885878250002861, 50...","(0.005617663264274597, 0.032484930008649826, 4...","(0.00536847161129117, 0.03531976416707039, 48....","(0.004834458697587252, 0.036590926349163055, 4...","(0.0053826491348445415, 0.02984020486474037, 4...","(0.005566434934735298, 0.0357804037630558, 48....","(0.004859181120991707, 0.03730365261435509, 47...","(0.005249732173979282, 0.03164418041706085, 48..."
7.0,"(0.034826889634132385, 0.1035953164100647, 101...","(0.01671607978641987, 0.07023420184850693, 79....","(0.012208264321088791, 0.0536700114607811, 70....","(0.009096970781683922, 0.049076199531555176, 6...","(0.007705571595579386, 0.037851009517908096, 5...","(0.0071730464696884155, 0.03771562501788139, 5...","(0.006538943387567997, 0.03417769819498062, 49...","(0.0070403204299509525, 0.04041583091020584, 5...","(0.005875390488654375, 0.04052955284714699, 52...","(0.005860080476850271, 0.03858306631445885, 52...","(0.00594245595857501, 0.03600132837891579, 48....","(0.005801240913569927, 0.0375266969203949, 49....","(0.005374522879719734, 0.03918194770812988, 52...","(0.005144577473402023, 0.037478093057870865, 4...","(0.005735979415476322, 0.041744329035282135, 5...","(0.005368868820369244, 0.035825468599796295, 4...","(0.005135920364409685, 0.03549619019031525, 51...","(0.005684231873601675, 0.04311205446720123, 53...","(0.0054719396866858006, 0.03407415747642517, 5...","(0.005457340739667416, 0.032932888716459274, 4..."
7.5,"(0.03265539929270744, 0.09013737738132477, 96....","(0.015844937413930893, 0.06953345239162445, 77...","(0.011453894898295403, 0.05215330049395561, 68...","(0.00921208132058382, 0.04994487762451172, 61....","(0.007646516431123018, 0.04510381817817688, 57...","(0.007608730811625719, 0.0375528559088707, 53....","(0.006460603792220354, 0.04468502849340439, 56...","(0.006459805183112621, 0.034082092344760895, 5...","(0.005669835489243269, 0.04035979136824608, 52...","(0.006167040206491947, 0.03414604067802429, 50...","(0.005528513342142105, 0.034412432461977005, 4...","(0.005474122706800699, 0.03846203535795212, 49...","(0.005488342605531216, 0.030763188377022743, 4...","(0.005410004407167435, 0.032557014375925064, 4...","(0.005275226663798094, 0.03746948763728142, 47...","(0.0053546493873000145, 0.03437120467424393, 4...","(0.005334140732884407, 0.029612446203827858, 4...","(0.005329232197254896, 0.03173830360174179, 46...","(0.0049161361530423164, 0.02525586076080799, 4...","(0.005402793642133474, 0.03806664049625397, 50..."
8.0,"(0.03353021666407585, 0.09640124440193176, 98....","(0.015193885192275047, 0.06197984144091606, 72...","(0.01202099397778511, 0.05178677663207054, 68....","(0.00967059563845396, 0.04469291865825653, 62....","(0.007847926579415798, 0.03677370399236679, 56...","(0.006655390840023756, 0.032287292182445526, 5...","(0.006068278104066849, 0.03305426612496376, 52...","(0.005696025211364031, 0.030263282358646393, 4...","(0.00556855509057641, 0.030658813193440437, 45...","(0.005482903681695461, 0.0289471298456192, 46....","(0.00569597352296114, 0.031937822699546814, 49...",931230,"(0.005070356652140617, 0.03279759734869003, 47...","(0.005352178122848272, 0.027204688638448715, 4...","(0.005198705941438675, 0.036570873111486435, 4...","(0.005076956935226917, 0.03043103963136673, 47...","(0.005347934551537037, 0.0316128134727478, 48....","(0.004763021599501371, 0.029325129464268684, 4...","(0.005447655450552702, 0.033303506672382355, 4...","(0.0049551320262253284, 0.022970041260123253, ..."
8.5,"(0.03379112482070923, 0.0880502313375473, 96.3...","(0.01604466512799263, 0.06223554536700249, 75....","(0.011292015202343464, 0.04759421572089195, 66...","(0.008943110704421997, 0.039764419198036194, 5...","(0.00743134506046772, 0.036810729652643204, 56...","(0.006750963628292084, 0.0354003943502903, 50....","(0.006830072030425072, 0.029166581109166145, 5...","(0.005896212067455053, 0.03148734197020531, 49...","(0.005383245646953583, 0.03561098873615265, 48...","(0.005987212993204594, 0.032250452786684036, 5...","(0.005289030261337757, 0.031870272010564804, 4...","(0.005465064197778702, 0.035392578691244125, 5...","(0.005032169632613659, 0.025606969371438026, 4...","(0.005422494374215603, 0.03183239325881004, 47...","(0.004761334042996168, 0.028014225885272026, 4...","(0.005311668384820223, 0.03172776848077774, 44...","(0.005180285777896643, 0.02595936879515648, 44...","(0.005326959770172834, 0.029514798894524574, 4...","(0.005375017412006855, 0.03489433601498604, 47...","(0.0047808303497731686, 0.035005345940589905, ..."
9.0,"(0.035336267203092575, 0.09309927374124527, 10...","(0.016150277107954025, 0.05926726758480072, 74...","(0.010411432944238186, 0.04825172573328018, 64...","(0.008929798379540443, 0.042194101959466934, 6...","(0.008062540553510189, 0.043799374252557755, 5...","(0.006467544473707676, 0.04175644367933273, 52...","(0.00622589560225606, 0.03243613615632057, 47....","(0.006233979482203722, 0.03752775117754936, 52...","(0.005912493914365768, 0.03631056100130081, 49...","(0.00562010845169425, 0.031767845153808594, 48...","(0.005590609274804592, 0.03444676101207733, 48...","(0.0051664868369698524, 0.03222218528389931, 4...","(0.005528096575289965, 0.030723754316568375, 4...","(0.005713541992008686, 0.030248837545514107, 4...","(0.005211951211094856, 0.03373594209551811, 46...","(0.004950207192450762, 0.024880124256014824, 4...","(0.004825123585760593, 0.025953402742743492, 4...","(0.004888046998530626, 0.0332517996430397, 45....","(0.0048829251900315285, 0.028565114364027977, ...","(0.004594238940626383, 0.030245672911405563, 4..."
9.5,"(0.03198602795600891, 0.09493272006511688, 99....","(0.015933269634842873, 0.053861502557992935, 7...","(0.011284480802714825, 0.05547337234020233, 66...","(0.009360114112496376, 0.04071209207177162, 61...","(0.007030099164694548, 0.03365158662199974, 54...","(0.0061899879947304726, 0.039601027965545654, ...","(0.0063003855757415295, 0.03383524343371391, 5...","(0.00567017262801528, 0.02858802117407322, 47....","(0.005184774752706289, 0.03298830986022949, 49...","(0.005902894306927919, 0.028183532878756523, 4...","(0.005364294163882732, 0.032857026904821396, 4...","(0.004685249645262957, 0.025980470702052116, 4...","(0.005386268254369497, 0.03162736818194389, 47...","(0.005345889832824469, 0.026870643720030785, 4...","(0.005079861730337143, 0.028045516461133957, 4...","(0.0052487654611468315, 0.028393466025590897, ...","(0.004773211665451527, 0.03319074958562851, 45...","(0.004883641377091408, 0.024174761027097702, 4...","(0.004606741480529308, 0.026967326179146767, 4...","(0.004972316790372133, 0.029580458998680115, 4..."